title: Chris Breezy's Blog
description: A blog about tech, programming, and life.

remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one